import 'dart:typed_data';

import 'package:share_plus/share_plus.dart';

/// Hands generated bytes to the OS under [filename].
///
/// The seam every "download this" action is injected with, so widget tests can
/// assert what would be shared without touching a platform channel.
typedef FileSharer = Future<void> Function(Uint8List bytes, String filename);

/// Default [FileSharer] behaviour: a browser download on the web PWA, the
/// share sheet on Android/iOS.
///
/// [Share.shareXFiles] is passed `fileNameOverrides` as well as the `XFile`'s
/// own name because an `XFile.fromData` has no path for the platform channel to
/// read a name from — without the override the file arrives named after a temp
/// handle on some platforms.
Future<void> shareBytes(
  Uint8List bytes,
  String filename,
  String mimeType,
) async {
  await Share.shareXFiles(
    [XFile.fromData(bytes, mimeType: mimeType, name: filename)],
    fileNameOverrides: [filename],
  );
}

Future<void> shareCsvFile(Uint8List bytes, String filename) =>
    shareBytes(bytes, filename, 'text/csv');

Future<void> sharePdfFile(Uint8List bytes, String filename) =>
    shareBytes(bytes, filename, 'application/pdf');

/// Turns a screen title into a filename-safe slug: lowercased, non-alphanumeric
/// runs collapsed to single dashes, no leading/trailing dash.
///
/// Windows, Android and iOS each reject a different set of characters in file
/// names, so this keeps only the intersection that is safe everywhere rather
/// than blocklisting per platform.
String filenameSlug(String value) {
  final slug = value
      .toLowerCase()
      .replaceAll(RegExp(r'[^a-z0-9]+'), '-')
      .replaceAll(RegExp(r'^-+|-+$'), '');
  return slug.isEmpty ? 'export' : slug;
}

/// `yyyy-MM-dd` for stamping a filename, so exports sort chronologically.
String filenameDate(DateTime when) =>
    '${when.year.toString().padLeft(4, '0')}-'
    '${when.month.toString().padLeft(2, '0')}-'
    '${when.day.toString().padLeft(2, '0')}';
